// Autogenerated from Pigeon (v26.1.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsCameraApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsCameraApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsCameraApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashCameraApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashCameraApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys {
      hasher.combine(key)
      deepHashCameraApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}



/// Generated class from Pigeon that represents data sent in messages.
struct CameraSnapshot: Hashable {
  var ready: Bool
  var front: Bool
  var configurationId: String
  var aspectRatio: Double
  var minimumEV: Double
  var maximumEV: Double
  var currentEV: Double
  var supportsLock: Bool
  var locked: Bool
  var minimumZoom: Double? = nil
  var maximumZoom: Double? = nil
  var currentZoom: Double? = nil
  var supportsTap: Bool? = nil
  var minimumISO: Double? = nil
  var maximumISO: Double? = nil
  var minimumShutter: Double? = nil
  var maximumShutter: Double? = nil
  var currentISO: Double? = nil
  var currentShutter: Double? = nil
  var manualExposure: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CameraSnapshot? {
    let ready = pigeonVar_list[0] as! Bool
    let front = pigeonVar_list[1] as! Bool
    let configurationId = pigeonVar_list[2] as! String
    let aspectRatio = pigeonVar_list[3] as! Double
    let minimumEV = pigeonVar_list[4] as! Double
    let maximumEV = pigeonVar_list[5] as! Double
    let currentEV = pigeonVar_list[6] as! Double
    let supportsLock = pigeonVar_list[7] as! Bool
    let locked = pigeonVar_list[8] as! Bool
    let minimumZoom: Double? = nilOrValue(pigeonVar_list[9])
    let maximumZoom: Double? = nilOrValue(pigeonVar_list[10])
    let currentZoom: Double? = nilOrValue(pigeonVar_list[11])
    let supportsTap: Bool? = nilOrValue(pigeonVar_list[12])
    let minimumISO: Double? = nilOrValue(pigeonVar_list[13])
    let maximumISO: Double? = nilOrValue(pigeonVar_list[14])
    let minimumShutter: Double? = nilOrValue(pigeonVar_list[15])
    let maximumShutter: Double? = nilOrValue(pigeonVar_list[16])
    let currentISO: Double? = nilOrValue(pigeonVar_list[17])
    let currentShutter: Double? = nilOrValue(pigeonVar_list[18])
    let manualExposure: Bool? = nilOrValue(pigeonVar_list[19])

    return CameraSnapshot(
      ready: ready,
      front: front,
      configurationId: configurationId,
      aspectRatio: aspectRatio,
      minimumEV: minimumEV,
      maximumEV: maximumEV,
      currentEV: currentEV,
      supportsLock: supportsLock,
      locked: locked,
      minimumZoom: minimumZoom,
      maximumZoom: maximumZoom,
      currentZoom: currentZoom,
      supportsTap: supportsTap,
      minimumISO: minimumISO,
      maximumISO: maximumISO,
      minimumShutter: minimumShutter,
      maximumShutter: maximumShutter,
      currentISO: currentISO,
      currentShutter: currentShutter,
      manualExposure: manualExposure
    )
  }
  func toList() -> [Any?] {
    return [
      ready,
      front,
      configurationId,
      aspectRatio,
      minimumEV,
      maximumEV,
      currentEV,
      supportsLock,
      locked,
      minimumZoom,
      maximumZoom,
      currentZoom,
      supportsTap,
      minimumISO,
      maximumISO,
      minimumShutter,
      maximumShutter,
      currentISO,
      currentShutter,
      manualExposure,
    ]
  }
  static func == (lhs: CameraSnapshot, rhs: CameraSnapshot) -> Bool {
    return deepEqualsCameraApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCameraApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PhotoHandle: Hashable {
  var path: String
  var id: String
  var unsaved: Bool
  var mimeType: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PhotoHandle? {
    let path = pigeonVar_list[0] as! String
    let id = pigeonVar_list[1] as! String
    let unsaved = pigeonVar_list[2] as! Bool
    let mimeType: String? = nilOrValue(pigeonVar_list[3])

    return PhotoHandle(
      path: path,
      id: id,
      unsaved: unsaved,
      mimeType: mimeType
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      id,
      unsaved,
      mimeType,
    ]
  }
  static func == (lhs: PhotoHandle, rhs: PhotoHandle) -> Bool {
    return deepEqualsCameraApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCameraApi(value: toList(), hasher: &hasher)
  }
}

private class CameraApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return CameraSnapshot.fromList(self.readValue() as! [Any?])
    case 130:
      return PhotoHandle.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CameraApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CameraSnapshot {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PhotoHandle {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CameraApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CameraApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CameraApiPigeonCodecWriter(data: data)
  }
}

class CameraApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CameraApiPigeonCodec(readerWriter: CameraApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CameraHostApi {
  func start(front: Bool, completion: @escaping (Result<CameraSnapshot, Error>) -> Void)
  func stop() throws
  func capture(completion: @escaping (Result<PhotoHandle, Error>) -> Void)
  func recover() throws -> PhotoHandle?
  func save(photo: PhotoHandle, completion: @escaping (Result<Void, Error>) -> Void)
  func discard(photo: PhotoHandle) throws
  func share(photo: PhotoHandle, completion: @escaping (Result<Void, Error>) -> Void)
  func pickPhoto(completion: @escaping (Result<PhotoHandle?, Error>) -> Void)
  func render(original: PhotoHandle, rotationDegrees: Double, crop: Bool, strength: Double, completion: @escaping (Result<PhotoHandle, Error>) -> Void)
  func setControls(configurationId: String, ev: Double, locked: Bool, completion: @escaping (Result<CameraSnapshot, Error>) -> Void)
  func renderStyle(original: PhotoHandle, matrix: [Double], softness: Double, detail: Double, watermarkPath: String?, completion: @escaping (Result<PhotoHandle, Error>) -> Void)
  func setVoicePhrase(phrase: String) throws
  func releasePhoto(photo: PhotoHandle) throws
  func setZoom(configurationId: String, zoom: Double, completion: @escaping (Result<CameraSnapshot, Error>) -> Void)
  func meter(configurationId: String, x: Double, y: Double, completion: @escaping (Result<CameraSnapshot, Error>) -> Void)
  func setManualExposure(configurationId: String, seconds: Double?, iso: Double?, completion: @escaping (Result<CameraSnapshot, Error>) -> Void)
  func openSettings() throws
  func setVoiceEnabled(enabled: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CameraHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CameraApiPigeonCodec.shared }
  /// Sets up an instance of `CameraHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CameraHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let frontArg = args[0] as! Bool
        api.start(front: frontArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    let captureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.capture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      captureChannel.setMessageHandler { _, reply in
        api.capture { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      captureChannel.setMessageHandler(nil)
    }
    let recoverChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.recover\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      recoverChannel.setMessageHandler { _, reply in
        do {
          let result = try api.recover()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      recoverChannel.setMessageHandler(nil)
    }
    let saveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.save\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let photoArg = args[0] as! PhotoHandle
        api.save(photo: photoArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveChannel.setMessageHandler(nil)
    }
    let discardChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.discard\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      discardChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let photoArg = args[0] as! PhotoHandle
        do {
          try api.discard(photo: photoArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      discardChannel.setMessageHandler(nil)
    }
    let shareChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.share\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      shareChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let photoArg = args[0] as! PhotoHandle
        api.share(photo: photoArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      shareChannel.setMessageHandler(nil)
    }
    let pickPhotoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.pickPhoto\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickPhotoChannel.setMessageHandler { _, reply in
        api.pickPhoto { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickPhotoChannel.setMessageHandler(nil)
    }
    let renderChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.render\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      renderChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let originalArg = args[0] as! PhotoHandle
        let rotationDegreesArg = args[1] as! Double
        let cropArg = args[2] as! Bool
        let strengthArg = args[3] as! Double
        api.render(original: originalArg, rotationDegrees: rotationDegreesArg, crop: cropArg, strength: strengthArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      renderChannel.setMessageHandler(nil)
    }
    let setControlsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.setControls\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setControlsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationIdArg = args[0] as! String
        let evArg = args[1] as! Double
        let lockedArg = args[2] as! Bool
        api.setControls(configurationId: configurationIdArg, ev: evArg, locked: lockedArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setControlsChannel.setMessageHandler(nil)
    }
    let renderStyleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.renderStyle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      renderStyleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let originalArg = args[0] as! PhotoHandle
        let matrixArg = args[1] as! [Double]
        let softnessArg = args[2] as! Double
        let detailArg = args[3] as! Double
        let watermarkPathArg: String? = nilOrValue(args[4])
        api.renderStyle(original: originalArg, matrix: matrixArg, softness: softnessArg, detail: detailArg, watermarkPath: watermarkPathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      renderStyleChannel.setMessageHandler(nil)
    }
    let setVoicePhraseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.setVoicePhrase\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVoicePhraseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let phraseArg = args[0] as! String
        do {
          try api.setVoicePhrase(phrase: phraseArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setVoicePhraseChannel.setMessageHandler(nil)
    }
    let releasePhotoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.releasePhoto\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releasePhotoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let photoArg = args[0] as! PhotoHandle
        do {
          try api.releasePhoto(photo: photoArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      releasePhotoChannel.setMessageHandler(nil)
    }
    let setZoomChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.setZoom\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setZoomChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationIdArg = args[0] as! String
        let zoomArg = args[1] as! Double
        api.setZoom(configurationId: configurationIdArg, zoom: zoomArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setZoomChannel.setMessageHandler(nil)
    }
    let meterChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.meter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      meterChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationIdArg = args[0] as! String
        let xArg = args[1] as! Double
        let yArg = args[2] as! Double
        api.meter(configurationId: configurationIdArg, x: xArg, y: yArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      meterChannel.setMessageHandler(nil)
    }
    let setManualExposureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.setManualExposure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setManualExposureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationIdArg = args[0] as! String
        let secondsArg: Double? = nilOrValue(args[1])
        let isoArg: Double? = nilOrValue(args[2])
        api.setManualExposure(configurationId: configurationIdArg, seconds: secondsArg, iso: isoArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setManualExposureChannel.setMessageHandler(nil)
    }
    let openSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.openSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openSettingsChannel.setMessageHandler { _, reply in
        do {
          try api.openSettings()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openSettingsChannel.setMessageHandler(nil)
    }
    let setVoiceEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.setVoiceEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVoiceEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        api.setVoiceEnabled(enabled: enabledArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setVoiceEnabledChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol CameraEventsProtocol {
  func analysis(json jsonArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func state(snapshot snapshotArg: CameraSnapshot, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func error(code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func voiceShutter(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class CameraEvents: CameraEventsProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: CameraApiPigeonCodec {
    return CameraApiPigeonCodec.shared
  }
  func analysis(json jsonArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.dali_camera_platform.CameraEvents.analysis\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([jsonArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func state(snapshot snapshotArg: CameraSnapshot, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.dali_camera_platform.CameraEvents.state\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([snapshotArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func error(code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.dali_camera_platform.CameraEvents.error\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([codeArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func voiceShutter(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.dali_camera_platform.CameraEvents.voiceShutter\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
