// Generated by tools/export_native_processing.py from the native reference.
import Foundation
import CoreGraphics

struct ReferencePoseGeometry {
    func poseAnalysis(
        from points: [String: DetectionPoint],
        person: DetectionBox?,
        face: DetectionBox?
    ) -> PoseAnalysis? {
        guard !points.isEmpty else { return nil }

        let visiblePoints = points.values.filter { $0.confidence > 0.2 }
        let confidence = visiblePoints.isEmpty
            ? 0
            : visiblePoints.reduce(0) { $0 + Double($1.confidence) } / Double(visiblePoints.count)

        let leftShoulder = point(namedAny: ["leftShoulder"], in: points)
        let rightShoulder = point(namedAny: ["rightShoulder"], in: points)
        let leftHip = point(namedAny: ["leftHip", "leftUpLeg"], in: points)
        let rightHip = point(namedAny: ["rightHip", "rightUpLeg"], in: points)
        let leftWrist = point(namedAny: ["leftWrist", "leftHand"], in: points)
        let rightWrist = point(namedAny: ["rightWrist", "rightHand"], in: points)
        let leftElbow = point(namedAny: ["leftElbow", "leftForearm"], in: points)
        let rightElbow = point(namedAny: ["rightElbow", "rightForearm"], in: points)
        let leftAnkle = point(namedAny: ["leftAnkle", "leftFoot"], in: points)
        let rightAnkle = point(namedAny: ["rightAnkle", "rightFoot"], in: points)
        let neck = point(namedAny: ["neck"], in: points)
        let nose = point(namedAny: ["nose", "head"], in: points)

        let shoulderLineAngle = angleDegrees(from: leftShoulder?.point, to: rightShoulder?.point)
        let shoulderHeightAsymmetry = normalizedVerticalDelta(leftShoulder?.point, rightShoulder?.point, person: person)
        let shoulderMid = midpoint(leftShoulder?.point, rightShoulder?.point)
        let hipMid = midpoint(leftHip?.point, rightHip?.point)
        let torsoAngle = angleDegrees(from: shoulderMid, to: hipMid).map { $0 - 90 }
        let shoulderWidth = distance(leftShoulder?.point, rightShoulder?.point)
        let hipWidth = distance(leftHip?.point, rightHip?.point)
        let bodySquareness = zipValues(shoulderWidth, hipWidth).map { shoulder, hip in
            min(1, max(0, shoulder / max(0.001, hip)) / 1.35)
        }
        let bodyProfile = bodySquareness.map { 1 - $0 }

        let wristFaceDistance = [leftWrist, rightWrist]
            .compactMap { wrist in distanceFrom(point: wrist?.point, to: face?.rect) }
            .min()
        let torsoRect = rectContaining([leftShoulder?.point, rightShoulder?.point, leftHip?.point, rightHip?.point].compactMap { $0 })
        let elbowTorsoDistances = [leftElbow, rightElbow]
            .compactMap { elbow in distanceFrom(point: elbow?.point, to: torsoRect) }
        let wristTorsoDistances = [leftWrist, rightWrist]
            .compactMap { wrist in distanceFrom(point: wrist?.point, to: torsoRect) }
        let armTorsoDistances = elbowTorsoDistances + wristTorsoDistances
        let armsFlat = armTorsoDistances.isEmpty
            ? nil
            : min(1, max(0, (0.055 - (armTorsoDistances.reduce(0, +) / Double(armTorsoDistances.count))) / 0.055))
        let wristEdgeDistance = [leftWrist, rightWrist]
            .compactMap { wrist in edgeDistance(wrist?.point) }
            .min()
        let visibleArmJoints = [leftShoulder, rightShoulder, leftElbow, rightElbow, leftWrist, rightWrist]
            .filter { ($0?.confidence ?? 0) > 0.2 }
            .count
        let armVisibility = Double(visibleArmJoints) / 6
        let stanceWidth = distance(leftAnkle?.point, rightAnkle?.point)
        let headToTorsoRatio = zipValues(face?.rect.height, distance(shoulderMid, hipMid)).map { head, torso in
            Double(head / max(0.001, torso))
        }
        let headAnchor = nose?.point ?? face.map { CGPoint(x: $0.rect.midX, y: $0.rect.midY) }
        let shoulderAnchor = neck?.point ?? shoulderMid
        let shouldersHigh = zipValues(headAnchor, shoulderAnchor).map { head, shoulder in
            let reference = Double(person?.rect.height ?? 1)
            return min(1, max(0, (0.16 - Double(abs(shoulder.y - head.y)) / max(0.001, reference)) / 0.16))
        }

        return PoseAnalysis(
            confidence: confidence,
            visibleKeypointCount: visiblePoints.count,
            shoulderLineAngleDegrees: shoulderLineAngle,
            shoulderHeightAsymmetry: shoulderHeightAsymmetry,
            torsoAngleDegrees: torsoAngle,
            wristToFaceDistance: wristFaceDistance,
            armVisibilityScore: armVisibility,
            stanceWidth: stanceWidth,
            headToTorsoRatio: headToTorsoRatio,
            shouldersHighScore: shouldersHigh,
            bodySquarenessScore: bodySquareness,
            bodyProfileScore: bodyProfile,
            armsFlatAgainstBodyScore: armsFlat,
            minWristEdgeDistance: wristEdgeDistance
        )
    }

    func point(named name: String, in points: [String: DetectionPoint]) -> DetectionPoint? {
        let target = normalizedJointName(name)
        return points.first { entry in
            normalizedJointName(entry.key).contains(target)
        }?.value
    }

    func normalizedJointName(_ name: String) -> String {
        name.lowercased().filter { $0.isLetter || $0.isNumber }
    }

    func midpoint(_ first: CGPoint?, _ second: CGPoint?) -> CGPoint? {
        guard let first, let second else { return nil }
        return CGPoint(x: (first.x + second.x) / 2, y: (first.y + second.y) / 2)
    }

    func distance(_ first: CGPoint?, _ second: CGPoint?) -> Double? {
        guard let first, let second else { return nil }
        return hypot(Double(first.x - second.x), Double(first.y - second.y))
    }

    func distanceFrom(point: CGPoint?, to rect: CGRect?) -> Double? {
        guard let point, let rect else { return nil }
        if rect.contains(point) { return 0 }

        let dx = max(rect.minX - point.x, 0, point.x - rect.maxX)
        let dy = max(rect.minY - point.y, 0, point.y - rect.maxY)
        return hypot(Double(dx), Double(dy))
    }

    func edgeDistance(_ point: CGPoint?) -> Double? {
        guard let point else { return nil }
        return Double(min(point.x, point.y, 1 - point.x, 1 - point.y))
    }

    func rectContaining(_ points: [CGPoint]) -> CGRect? {
        guard let first = points.first else { return nil }
        var minX = first.x
        var minY = first.y
        var maxX = first.x
        var maxY = first.y

        for point in points.dropFirst() {
            minX = min(minX, point.x)
            minY = min(minY, point.y)
            maxX = max(maxX, point.x)
            maxY = max(maxY, point.y)
        }

        return CGRect(x: minX, y: minY, width: max(0.001, maxX - minX), height: max(0.001, maxY - minY))
    }

    func angleDegrees(from first: CGPoint?, to second: CGPoint?) -> Double? {
        guard let first, let second else { return nil }
        return atan2(Double(second.y - first.y), Double(second.x - first.x)) * 180 / .pi
    }

    func normalizedVerticalDelta(_ first: CGPoint?, _ second: CGPoint?, person: DetectionBox?) -> Double? {
        guard let first, let second else { return nil }
        return Double(abs(first.y - second.y) / max(0.001, person?.rect.height ?? 1))
    }

    func zipValues<A, B>(_ first: A?, _ second: B?) -> (A, B)? {
        guard let first, let second else { return nil }
        return (first, second)
    }

    func point(namedAny names: [String], in points: [String: DetectionPoint]) -> DetectionPoint? {
        for name in names {
            if let point = point(named: name, in: points) {
                return point
            }
        }

        return nil
    }
}
