// Generated by tools/export_native_processing.py from the native reference.
import UIKit
import Vision
import CoreImage

struct ReferenceMeasurementAlgorithms {
    private let coachingEngine = CoachingEngine()
    func normalizedTopLeftRect(_ rect: CGRect) -> CGRect {
        CGRect(x: rect.minX, y: 1 - rect.maxY, width: rect.width, height: rect.height)
    }

    func salientObject(
        from request: VNGenerateObjectnessBasedSaliencyImageRequest
    ) -> DetectionBox? {
        guard let objects = request.results?.first?.salientObjects else { return nil }
        return objects
            .map {
                DetectionBox(
                    rect: normalizedTopLeftRect($0.boundingBox),
                    confidence: CGFloat($0.confidence),
                    label: "salient_object"
                )
            }
            .max { first, second in
                first.rect.width * first.rect.height < second.rect.width * second.rect.height
            }
    }

    func estimatePersonFromFace(_ face: DetectionBox) -> DetectionBox {
        let faceRect = face.rect
        let width = min(0.9, faceRect.width * 3.0)
        let height = min(0.95, faceRect.height * 6.2)
        let x = max(0, min(1 - width, faceRect.midX - width / 2))
        let y = max(0, min(1 - height, faceRect.minY - faceRect.height * 0.45))
        return DetectionBox(rect: CGRect(x: x, y: y, width: width, height: height), confidence: face.confidence * 0.72, label: "person_estimated")
    }

    func groupAnalysis(people: [DetectionBox], faces: [DetectionBox]) -> GroupAnalysis? {
        let personLikeBoxes = people.isEmpty ? faces.map { estimatePersonFromFace($0) } : people
        guard personLikeBoxes.count > 1 || faces.count > 1 else { return nil }

        let groupBounds = rectContainingRects(personLikeBoxes.map(\.rect))
        let faceVisibilityRatio = Double(faces.count) / Double(max(1, personLikeBoxes.count))
        let nearestEdge = personLikeBoxes
            .flatMap { box in
                [
                    Double(box.rect.minX),
                    Double(box.rect.minY),
                    Double(1 - box.rect.maxX),
                    Double(1 - box.rect.maxY)
                ]
            }
            .min() ?? 1
        let edgeCrowding = min(1, max(0, (0.06 - nearestEdge) / 0.06))
        let centers = personLikeBoxes.map { Double($0.rect.midX) }.sorted()
        let gaps = zip(centers, centers.dropFirst()).map { $1 - $0 }
        let averageWidth = personLikeBoxes.reduce(0) { $0 + Double($1.rect.width) } / Double(personLikeBoxes.count)
        let spacingScore = gaps.isEmpty
            ? nil
            : max(0, (gaps.reduce(0, +) / Double(gaps.count)) / max(0.001, averageWidth))

        return GroupAnalysis(
            peopleCount: personLikeBoxes.count,
            faceCount: faces.count,
            groupBounds: groupBounds,
            faceVisibilityRatio: min(1, faceVisibilityRatio),
            edgeCrowdingScore: edgeCrowding,
            spacingScore: spacingScore
        )
    }

    func poseKeypoints(from observations: [VNHumanBodyPoseObservation]) -> [String: DetectionPoint] {
        guard let observation = observations.max(by: { $0.confidence < $1.confidence }),
              let recognizedPoints = try? observation.recognizedPoints(.all) else {
            return [:]
        }

        return recognizedPoints.reduce(into: [String: DetectionPoint]()) { result, entry in
            guard entry.value.confidence > 0.15 else { return }
            result[String(describing: entry.key)] = DetectionPoint(
                point: CGPoint(x: entry.value.location.x, y: 1 - entry.value.location.y),
                confidence: CGFloat(entry.value.confidence)
            )
        }
    }

    func poseAnalysis(
        from points: [String: DetectionPoint],
        person: DetectionBox?,
        face: DetectionBox?
    ) -> PoseAnalysis? {
        guard !points.isEmpty else { return nil }

        let visiblePoints = points.values.filter { $0.confidence > 0.2 }
        let confidence = visiblePoints.isEmpty
            ? 0
            : visiblePoints.reduce(0) { $0 + Double($1.confidence) } / Double(visiblePoints.count)

        let leftShoulder = point(namedAny: ["leftShoulder"], in: points)
        let rightShoulder = point(namedAny: ["rightShoulder"], in: points)
        let leftHip = point(namedAny: ["leftHip", "leftUpLeg"], in: points)
        let rightHip = point(namedAny: ["rightHip", "rightUpLeg"], in: points)
        let leftWrist = point(namedAny: ["leftWrist", "leftHand"], in: points)
        let rightWrist = point(namedAny: ["rightWrist", "rightHand"], in: points)
        let leftElbow = point(namedAny: ["leftElbow", "leftForearm"], in: points)
        let rightElbow = point(namedAny: ["rightElbow", "rightForearm"], in: points)
        let leftAnkle = point(namedAny: ["leftAnkle", "leftFoot"], in: points)
        let rightAnkle = point(namedAny: ["rightAnkle", "rightFoot"], in: points)
        let neck = point(namedAny: ["neck"], in: points)
        let nose = point(namedAny: ["nose", "head"], in: points)

        let shoulderLineAngle = angleDegrees(from: leftShoulder?.point, to: rightShoulder?.point)
        let shoulderHeightAsymmetry = normalizedVerticalDelta(leftShoulder?.point, rightShoulder?.point, person: person)
        let shoulderMid = midpoint(leftShoulder?.point, rightShoulder?.point)
        let hipMid = midpoint(leftHip?.point, rightHip?.point)
        let torsoAngle = angleDegrees(from: shoulderMid, to: hipMid).map { $0 - 90 }
        let shoulderWidth = distance(leftShoulder?.point, rightShoulder?.point)
        let hipWidth = distance(leftHip?.point, rightHip?.point)
        let bodySquareness = zipValues(shoulderWidth, hipWidth).map { shoulder, hip in
            min(1, max(0, shoulder / max(0.001, hip)) / 1.35)
        }
        let bodyProfile = bodySquareness.map { 1 - $0 }

        let wristFaceDistance = [leftWrist, rightWrist]
            .compactMap { wrist in distanceFrom(point: wrist?.point, to: face?.rect) }
            .min()
        let torsoRect = rectContaining([leftShoulder?.point, rightShoulder?.point, leftHip?.point, rightHip?.point].compactMap { $0 })
        let elbowTorsoDistances = [leftElbow, rightElbow]
            .compactMap { elbow in distanceFrom(point: elbow?.point, to: torsoRect) }
        let wristTorsoDistances = [leftWrist, rightWrist]
            .compactMap { wrist in distanceFrom(point: wrist?.point, to: torsoRect) }
        let armTorsoDistances = elbowTorsoDistances + wristTorsoDistances
        let armsFlat = armTorsoDistances.isEmpty
            ? nil
            : min(1, max(0, (0.055 - (armTorsoDistances.reduce(0, +) / Double(armTorsoDistances.count))) / 0.055))
        let wristEdgeDistance = [leftWrist, rightWrist]
            .compactMap { wrist in edgeDistance(wrist?.point) }
            .min()
        let visibleArmJoints = [leftShoulder, rightShoulder, leftElbow, rightElbow, leftWrist, rightWrist]
            .filter { ($0?.confidence ?? 0) > 0.2 }
            .count
        let armVisibility = Double(visibleArmJoints) / 6
        let stanceWidth = distance(leftAnkle?.point, rightAnkle?.point)
        let headToTorsoRatio = zipValues(face?.rect.height, distance(shoulderMid, hipMid)).map { head, torso in
            Double(head / max(0.001, torso))
        }
        let headAnchor = nose?.point ?? face.map { CGPoint(x: $0.rect.midX, y: $0.rect.midY) }
        let shoulderAnchor = neck?.point ?? shoulderMid
        let shouldersHigh = zipValues(headAnchor, shoulderAnchor).map { head, shoulder in
            let reference = Double(person?.rect.height ?? 1)
            return min(1, max(0, (0.16 - Double(abs(shoulder.y - head.y)) / max(0.001, reference)) / 0.16))
        }

        return PoseAnalysis(
            confidence: confidence,
            visibleKeypointCount: visiblePoints.count,
            shoulderLineAngleDegrees: shoulderLineAngle,
            shoulderHeightAsymmetry: shoulderHeightAsymmetry,
            torsoAngleDegrees: torsoAngle,
            wristToFaceDistance: wristFaceDistance,
            armVisibilityScore: armVisibility,
            stanceWidth: stanceWidth,
            headToTorsoRatio: headToTorsoRatio,
            shouldersHighScore: shouldersHigh,
            bodySquarenessScore: bodySquareness,
            bodyProfileScore: bodyProfile,
            armsFlatAgainstBodyScore: armsFlat,
            minWristEdgeDistance: wristEdgeDistance
        )
    }

    func faceAnalysis(from observation: VNFaceObservation?, face: DetectionBox?) -> FaceAnalysis? {
        guard let observation,
              let face,
              let landmarks = observation.landmarks else {
            return nil
        }

        let leftEye = landmarkPoints(landmarks.leftEye, in: face.rect)
        let rightEye = landmarkPoints(landmarks.rightEye, in: face.rect)
        let nose = landmarkPoints(landmarks.nose, in: face.rect)
        let outerLips = landmarkPoints(landmarks.outerLips, in: face.rect)
        let medianLine = landmarkPoints(landmarks.medianLine, in: face.rect)
        let allPoints = leftEye + rightEye + nose + outerLips + medianLine

        let eyeVisibility = Double([leftEye, rightEye].filter { $0.count >= 3 }.count) / 2
        let occlusion = min(1, max(0, 1 - (Double(allPoints.count) / 26)))
        let leftEyeCenter = center(of: leftEye)
        let rightEyeCenter = center(of: rightEye)
        let noseCenter = center(of: nose)
        let lipsCenter = center(of: outerLips)
        let eyeCenter = midpoint(leftEyeCenter, rightEyeCenter)
        let eyeSpan = distance(leftEyeCenter, rightEyeCenter)
        let yaw = zipValues(noseCenter, eyeCenter).flatMap { nose, eyes in
            eyeSpan.map { span in
                Double((nose.x - eyes.x) / max(0.001, CGFloat(span)))
            }
        }
        let pitch = zipValues(noseCenter, lipsCenter).map { nose, lips in
            Double((lips.y - nose.y) / max(0.001, face.rect.height))
        }

        return FaceAnalysis(
            confidence: Double(observation.confidence),
            landmarkPointCount: allPoints.count,
            eyeVisibilityScore: eyeVisibility,
            yawEstimate: yaw,
            pitchEstimate: pitch,
            occlusionScore: occlusion
        )
    }

    func faceLandmarkGeometry(
        from observation: VNFaceObservation?,
        face: DetectionBox?
    ) -> FaceLandmarkGeometry? {
        guard let observation, let face, let landmarks = observation.landmarks else {
            return nil
        }

        let geometry = FaceLandmarkGeometry(
            leftEye: landmarkPoints(landmarks.leftEye, in: face.rect),
            rightEye: landmarkPoints(landmarks.rightEye, in: face.rect),
            outerLips: landmarkPoints(landmarks.outerLips, in: face.rect),
            faceContour: landmarkPoints(landmarks.faceContour, in: face.rect)
        )
        return geometry.hasEyes || geometry.hasLips ? geometry : nil
    }

    func point(named name: String, in points: [String: DetectionPoint]) -> DetectionPoint? {
        let target = normalizedJointName(name)
        return points.first { entry in
            normalizedJointName(entry.key).contains(target)
        }?.value
    }

    func normalizedJointName(_ name: String) -> String {
        name.lowercased().filter { $0.isLetter || $0.isNumber }
    }

    func midpoint(_ first: CGPoint?, _ second: CGPoint?) -> CGPoint? {
        guard let first, let second else { return nil }
        return CGPoint(x: (first.x + second.x) / 2, y: (first.y + second.y) / 2)
    }

    func distance(_ first: CGPoint?, _ second: CGPoint?) -> Double? {
        guard let first, let second else { return nil }
        return hypot(Double(first.x - second.x), Double(first.y - second.y))
    }

    func distanceFrom(point: CGPoint?, to rect: CGRect?) -> Double? {
        guard let point, let rect else { return nil }
        if rect.contains(point) { return 0 }

        let dx = max(rect.minX - point.x, 0, point.x - rect.maxX)
        let dy = max(rect.minY - point.y, 0, point.y - rect.maxY)
        return hypot(Double(dx), Double(dy))
    }

    func edgeDistance(_ point: CGPoint?) -> Double? {
        guard let point else { return nil }
        return Double(min(point.x, point.y, 1 - point.x, 1 - point.y))
    }

    func rectContaining(_ points: [CGPoint]) -> CGRect? {
        guard let first = points.first else { return nil }
        var minX = first.x
        var minY = first.y
        var maxX = first.x
        var maxY = first.y

        for point in points.dropFirst() {
            minX = min(minX, point.x)
            minY = min(minY, point.y)
            maxX = max(maxX, point.x)
            maxY = max(maxY, point.y)
        }

        return CGRect(x: minX, y: minY, width: max(0.001, maxX - minX), height: max(0.001, maxY - minY))
    }

    func rectContainingRects(_ rects: [CGRect]) -> CGRect? {
        guard let first = rects.first else { return nil }
        return rects.dropFirst().reduce(first) { $0.union($1) }
    }

    func center(of points: [CGPoint]) -> CGPoint? {
        guard !points.isEmpty else { return nil }
        let total = points.reduce(CGPoint.zero) { partial, point in
            CGPoint(x: partial.x + point.x, y: partial.y + point.y)
        }
        return CGPoint(x: total.x / CGFloat(points.count), y: total.y / CGFloat(points.count))
    }

    func landmarkPoints(_ region: VNFaceLandmarkRegion2D?, in faceRect: CGRect) -> [CGPoint] {
        guard let region else { return [] }
        return region.normalizedPoints.map { point in
            CGPoint(
                x: faceRect.minX + point.x * faceRect.width,
                y: faceRect.maxY - point.y * faceRect.height
            )
        }
    }

    func angleDegrees(from first: CGPoint?, to second: CGPoint?) -> Double? {
        guard let first, let second else { return nil }
        return atan2(Double(second.y - first.y), Double(second.x - first.x)) * 180 / .pi
    }

    func normalizedVerticalDelta(_ first: CGPoint?, _ second: CGPoint?, person: DetectionBox?) -> Double? {
        guard let first, let second else { return nil }
        return Double(abs(first.y - second.y) / max(0.001, person?.rect.height ?? 1))
    }

    func zipValues<A, B>(_ first: A?, _ second: B?) -> (A, B)? {
        guard let first, let second else { return nil }
        return (first, second)
    }

    func analyzeImage(
        cgImage: CGImage,
        orientation: CGImagePropertyOrientation
    ) throws -> (measurements: Measurements, issues: [PhotoIssue]) {
        let humanRequest = VNDetectHumanRectanglesRequest()
        humanRequest.upperBodyOnly = false
        let faceRequest = VNDetectFaceLandmarksRequest()
        let poseRequest = VNDetectHumanBodyPoseRequest()
        let horizonRequest = VNDetectHorizonRequest()
        let saliencyRequest = VNGenerateObjectnessBasedSaliencyImageRequest()
        let handler = VNImageRequestHandler(cgImage: cgImage, orientation: orientation, options: [:])

        do {
            try handler.perform([humanRequest, faceRequest, poseRequest, horizonRequest, saliencyRequest])
        } catch { throw error }

        let people = (humanRequest.results ?? [])
            .map {
                DetectionBox(
                    rect: normalizedTopLeftRect($0.boundingBox),
                    confidence: CGFloat($0.confidence),
                    label: "person"
                )
            }
            .filter { $0.confidence > 0.25 }

        let human = people
            .max { $0.confidence < $1.confidence }

        let faceObservations = faceRequest.results ?? []
        let faces = faceObservations
            .map {
                DetectionBox(
                    rect: normalizedTopLeftRect($0.boundingBox),
                    confidence: CGFloat($0.confidence),
                    label: "face"
                )
            }
            .filter { $0.confidence > 0.25 }

        let faceObservation = faceObservations
            .max { $0.confidence < $1.confidence }

        let face = faces.max { $0.confidence < $1.confidence }

        let person = human ?? face.map { estimatePersonFromFace($0) }
        let poseKeypoints = poseKeypoints(from: poseRequest.results ?? [])
        let horizon = horizonRequest.results?.first
        let measurements = stillMeasurements(
            person: person,
            face: face,
            groupAnalysis: groupAnalysis(people: people, faces: faces),
            faceAnalysis: faceAnalysis(from: faceObservation, face: face),
            poseKeypoints: poseKeypoints,
            poseAnalysis: poseAnalysis(from: poseKeypoints, person: person, face: face),
            faceLuminance: face.flatMap { luminance(in: cgImage, normalizedRect: $0.rect) },
            backgroundLuminance: luminance(in: cgImage, normalizedRect: nil),
            horizonAngleDegrees: horizon.map { Double($0.angle) * 180 / .pi },
            horizonConfidence: horizon == nil ? 0 : 0.72,
            skyOrOpenAreaRatio: skyOrOpenAreaRatio(in: cgImage),
            salientObjectBox: salientObject(from: saliencyRequest),
            faceLandmarks: faceLandmarkGeometry(from: faceObservation, face: face)
        )

        return (measurements, [])
    }

    func reframeSuggestion(for measurements: Measurements, imageSize: CGSize) -> ReframeSuggestion? {
        guard let person = measurements.personBox,
              person.confidence > 0.35,
              imageSize.width > 0,
              imageSize.height > 0 else {
            return nil
        }

        let imageAspectRatio = imageSize.width / imageSize.height
        let targetAspectRatio = imageAspectRatio < 1 ? CGFloat(3.0 / 4.0) : CGFloat(4.0 / 3.0)
        let personRect = person.rect
        let tightCrop = personRect.insetBy(dx: -personRect.width * 0.42, dy: -personRect.height * 0.18)
        var crop = tightCrop.union(CGRect(
            x: personRect.midX - personRect.width * 0.85,
            y: max(0, personRect.minY - 0.08),
            width: personRect.width * 1.7,
            height: personRect.height * 1.24
        ))

        crop = expand(crop, toAspectRatio: targetAspectRatio)
        crop = clamp(crop)

        let issues = coachingEngine.issues(for: measurements, includePosture: false)
        let instruction = reframeInstruction(for: issues, crop: crop)
        let fullFrame = CGRect(x: 0, y: 0, width: 1, height: 1)
        let cropChanged = abs(crop.minX - fullFrame.minX) > 0.02
            || abs(crop.minY - fullFrame.minY) > 0.02
            || abs(crop.width - fullFrame.width) > 0.02
            || abs(crop.height - fullFrame.height) > 0.02

        guard cropChanged else { return nil }

        return ReframeSuggestion(
            cropRect: crop,
            targetAspectRatio: targetAspectRatio,
            instruction: instruction,
            confidence: Double(person.confidence),
            reason: issues.first?.type ?? "balanced_crop"
        )
    }

    func reframeInstruction(for issues: [PhotoIssue], crop: CGRect) -> String {
        if issues.contains(where: { $0.type == "headroom_too_large" }) {
            return "Crop lower"
        }

        if issues.contains(where: { $0.type == "scene_excluded" || $0.type == "subject_too_close" }) {
            return "Use a wider frame"
        }

        if issues.contains(where: { $0.type == "subject_too_far" }) {
            return "Crop closer"
        }

        if crop.minX > 0.08 {
            return "Shift frame right"
        }

        if crop.maxX < 0.92 {
            return "Shift frame left"
        }

        return "Suggested reframe"
    }

    func expand(_ rect: CGRect, toAspectRatio aspectRatio: CGFloat) -> CGRect {
        var next = rect
        let currentAspectRatio = next.width / max(0.001, next.height)

        if currentAspectRatio < aspectRatio {
            let newWidth = next.height * aspectRatio
            next.origin.x -= (newWidth - next.width) / 2
            next.size.width = newWidth
        } else {
            let newHeight = next.width / aspectRatio
            next.origin.y -= (newHeight - next.height) / 2
            next.size.height = newHeight
        }

        return next
    }

    func clamp(_ rect: CGRect) -> CGRect {
        var next = rect
        next.size.width = min(1, max(0.1, next.width))
        next.size.height = min(1, max(0.1, next.height))
        next.origin.x = min(max(0, next.origin.x), 1 - next.width)
        next.origin.y = min(max(0, next.origin.y), 1 - next.height)
        return next
    }

    func croppedImage(_ image: UIImage, to normalizedRect: CGRect) -> UIImage? {
        guard let cgImage = image.cgImage else { return nil }

        let pixelRect = CGRect(
            x: normalizedRect.minX * CGFloat(cgImage.width),
            y: normalizedRect.minY * CGFloat(cgImage.height),
            width: normalizedRect.width * CGFloat(cgImage.width),
            height: normalizedRect.height * CGFloat(cgImage.height)
        ).integral

        guard let cropped = cgImage.cropping(to: pixelRect) else { return nil }
        return UIImage(cgImage: cropped, scale: image.scale, orientation: .up)
    }

    func leveledImage(_ image: UIImage, measurements: Measurements) -> UIImage? {
        guard let horizonAngle = measurements.horizonAngleDegrees,
              measurements.horizonConfidence > 0.55,
              abs(horizonAngle) > 3 else {
            return nil
        }

        return rotatedImage(image, degrees: -horizonAngle)
    }

    func rotatedImage(_ image: UIImage, degrees: Double) -> UIImage {
        let radians = CGFloat(degrees) * .pi / 180
        let sourceSize = image.size
        let rotatedRect = CGRect(origin: .zero, size: sourceSize)
            .applying(CGAffineTransform(rotationAngle: radians))
        let outputSize = CGSize(width: abs(rotatedRect.width), height: abs(rotatedRect.height))
        let format = UIGraphicsImageRendererFormat.default()
        format.scale = image.scale

        return UIGraphicsImageRenderer(size: outputSize, format: format).image { context in
            UIColor.black.setFill()
            context.fill(CGRect(origin: .zero, size: outputSize))
            context.cgContext.translateBy(x: outputSize.width / 2, y: outputSize.height / 2)
            context.cgContext.rotate(by: radians)
            image.draw(in: CGRect(
                x: -sourceSize.width / 2,
                y: -sourceSize.height / 2,
                width: sourceSize.width,
                height: sourceSize.height
            ))
        }
    }

    func stillMeasurements(
        person: DetectionBox?,
        face: DetectionBox?,
        groupAnalysis: GroupAnalysis? = nil,
        faceAnalysis: FaceAnalysis?,
        poseKeypoints: [String: DetectionPoint],
        poseAnalysis: PoseAnalysis?,
        faceLuminance: Double?,
        backgroundLuminance: Double?,
        horizonAngleDegrees: Double?,
        horizonConfidence: Double,
        skyOrOpenAreaRatio: Double,
        salientObjectBox: DetectionBox? = nil,
        faceLandmarks: FaceLandmarkGeometry? = nil
    ) -> Measurements {
        Measurements(
            personBox: person,
            faceBox: face,
            groupAnalysis: groupAnalysis,
            faceAnalysis: faceAnalysis,
            poseKeypoints: poseKeypoints,
            poseAnalysis: poseAnalysis,
            faceLuminance: faceLuminance,
            backgroundLuminance: backgroundLuminance,
            horizonAngleDegrees: horizonAngleDegrees,
            horizonY: horizonAngleDegrees == nil ? nil : 0.5,
            horizonConfidence: horizonConfidence,
            cameraRollDegrees: 0,
            cameraMotion: 0,
            cameraStable: true,
            skyOrOpenAreaRatio: skyOrOpenAreaRatio,
            timestamp: Date(),
            salientObjectBox: salientObjectBox,
            faceLandmarks: faceLandmarks
        )
    }

    func point(namedAny names: [String], in points: [String: DetectionPoint]) -> DetectionPoint? {
        for name in names {
            if let point = point(named: name, in: points) {
                return point
            }
        }

        return nil
    }

    func luminance(in cgImage: CGImage, normalizedRect: CGRect?) -> Double? {
        guard let dataProvider = cgImage.dataProvider,
              let data = dataProvider.data,
              let bytes = CFDataGetBytePtr(data),
              cgImage.bitsPerPixel >= 24 else {
            return nil
        }

        let width = cgImage.width
        let height = cgImage.height
        let bytesPerRow = cgImage.bytesPerRow
        let bytesPerPixel = max(1, cgImage.bitsPerPixel / 8)
        let rect = normalizedRect ?? CGRect(x: 0, y: 0, width: 1, height: 1)
        let minX = max(0, min(width - 1, Int(rect.minX * CGFloat(width))))
        let maxX = max(minX + 1, min(width, Int(rect.maxX * CGFloat(width))))
        let minY = max(0, min(height - 1, Int(rect.minY * CGFloat(height))))
        let maxY = max(minY + 1, min(height, Int(rect.maxY * CGFloat(height))))
        let step = max(1, min(width, height) / 100)
        let bitmapInfo = cgImage.bitmapInfo
        let alphaInfo = CGImageAlphaInfo(rawValue: bitmapInfo.rawValue & CGBitmapInfo.alphaInfoMask.rawValue)
        let byteOrder = bitmapInfo.intersection(.byteOrderMask)
        let alphaFirst = alphaInfo == .premultipliedFirst || alphaInfo == .first || alphaInfo == .noneSkipFirst
        let bgrOrder = byteOrder == .byteOrder32Little

        var total = 0.0
        var count = 0

        for y in stride(from: minY, to: maxY, by: step) {
            let row = bytes.advanced(by: y * bytesPerRow)
            for x in stride(from: minX, to: maxX, by: step) {
                let pixel = row.advanced(by: x * bytesPerPixel)
                let colorOffset = alphaFirst ? 1 : 0
                let redIndex = bgrOrder ? colorOffset + 2 : colorOffset
                let greenIndex = colorOffset + 1
                let blueIndex = bgrOrder ? colorOffset : colorOffset + 2

                guard max(redIndex, greenIndex, blueIndex) < bytesPerPixel else { continue }

                let red = Double(pixel[redIndex])
                let green = Double(pixel[greenIndex])
                let blue = Double(pixel[blueIndex])
                total += 0.2126 * red + 0.7152 * green + 0.0722 * blue
                count += 1
            }
        }

        return count > 0 ? total / Double(count) : nil
    }

    func skyOrOpenAreaRatio(in cgImage: CGImage) -> Double {
        guard let dataProvider = cgImage.dataProvider,
              let data = dataProvider.data,
              let bytes = CFDataGetBytePtr(data),
              cgImage.bitsPerPixel >= 24 else {
            return 0
        }

        let width = cgImage.width
        let height = cgImage.height
        let bytesPerRow = cgImage.bytesPerRow
        let bytesPerPixel = max(1, cgImage.bitsPerPixel / 8)
        let sampleMaxY = max(1, height / 3)
        let step = max(1, min(width, height) / 90)
        let bitmapInfo = cgImage.bitmapInfo
        let alphaInfo = CGImageAlphaInfo(rawValue: bitmapInfo.rawValue & CGBitmapInfo.alphaInfoMask.rawValue)
        let byteOrder = bitmapInfo.intersection(.byteOrderMask)
        let alphaFirst = alphaInfo == .premultipliedFirst || alphaInfo == .first || alphaInfo == .noneSkipFirst
        let bgrOrder = byteOrder == .byteOrder32Little

        var openPixels = 0
        var sampledPixels = 0

        for y in stride(from: 0, to: sampleMaxY, by: step) {
            let row = bytes.advanced(by: y * bytesPerRow)
            for x in stride(from: 0, to: width, by: step) {
                let pixel = row.advanced(by: x * bytesPerPixel)
                let colorOffset = alphaFirst ? 1 : 0
                let redIndex = bgrOrder ? colorOffset + 2 : colorOffset
                let greenIndex = colorOffset + 1
                let blueIndex = bgrOrder ? colorOffset : colorOffset + 2

                guard max(redIndex, greenIndex, blueIndex) < bytesPerPixel else { continue }

                let red = Double(pixel[redIndex])
                let green = Double(pixel[greenIndex])
                let blue = Double(pixel[blueIndex])
                let luminance = 0.2126 * red + 0.7152 * green + 0.0722 * blue
                let blueDominant = blue > red * 1.08 && blue > green * 0.95
                let brightOpen = luminance > 170

                if blueDominant || brightOpen {
                    openPixels += 1
                }
                sampledPixels += 1
            }
        }

        return sampledPixels > 0 ? Double(openPixels) / Double(sampledPixels) : 0
    }
}
