"""Export the frozen native processing code into the Flutter iOS module."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / "packages/dali_camera_platform/ios/dali_camera_platform/Sources/dali_camera_platform"
HEADER = "// Generated by tools/export_native_processing.py from the native reference.\n"


def function(source, name, marker=None):
    import re
    matches = list(re.finditer(r"    private (?:nonisolated )?func " + re.escape(name) + r"\b", source))
    for match in matches:
        start = match.start()
        brace = source.index("{", start)
        if marker and marker not in source[start:brace]:
            continue
        depth = 1
        end = brace + 1
        while depth:
            depth += (source[end] == "{") - (source[end] == "}")
            end += 1
        return source[start:end].replace("private nonisolated func", "func").replace("private func", "func")
    raise ValueError(name)


def outputs():
    result = {}
    for name in ["Models", "CoachingEngine", "EnhanceEngine", "BeautifyEngine"]:
        result["Reference" + name + ".swift"] = HEADER + (ROOT / f"DaliCamera/{name}.swift").read_text(encoding="utf-8")
    source = (ROOT / "DaliCamera/CameraModel.swift").read_text(encoding="utf-8")
    names = ["normalizedTopLeftRect", "salientObject", "estimatePersonFromFace", "groupAnalysis", "poseKeypoints", "poseAnalysis", "faceAnalysis", "faceLandmarkGeometry", "point", "normalizedJointName", "midpoint", "distance", "distanceFrom", "edgeDistance", "rectContaining", "rectContainingRects", "center", "landmarkPoints", "angleDegrees", "normalizedVerticalDelta", "zipValues", "analyzeImage", "reframeSuggestion", "reframeInstruction", "expand", "clamp", "croppedImage", "leveledImage", "rotatedImage", "stillMeasurements"]
    methods = [function(source, name) for name in names]
    # Keep detector failures independent and expose per-signal availability.
    index = names.index("analyzeImage")
    analysis = methods[index].replace(") -> (measurements:", ") throws -> (measurements:")
    begin = analysis.index("        do {")
    end = analysis.index("        let people =", begin)
    analysis = analysis.replace("issues: [PhotoIssue])", "issues: [PhotoIssue], availability: [String: String])")
    # Recompute indices after changing the return type.
    begin = analysis.index("        do {")
    end = analysis.index("        let people =", begin)
    analysis = analysis[:begin] + '''        var availability: [String: String] = [:]
        for (name, request) in [("people", humanRequest as VNRequest), ("face", faceRequest as VNRequest), ("pose", poseRequest as VNRequest), ("horizon", horizonRequest as VNRequest), ("saliency", saliencyRequest as VNRequest)] {
            do { try handler.perform([request]); availability[name] = "valid" }
            catch { availability[name] = "unavailable" }
        }

''' + analysis[end:]
    methods[index] = analysis.replace("return (measurements, [])", "return (measurements, [], availability)")
    methods += [function(source, "point", "namedAny"), function(source, "luminance", "cgImage"), function(source, "skyOrOpenAreaRatio", "cgImage")]
    pure_names = ["poseAnalysis", "point", "normalizedJointName", "midpoint", "distance", "distanceFrom", "edgeDistance", "rectContaining", "angleDegrees", "normalizedVerticalDelta", "zipValues"]
    pure = [function(source, name) for name in pure_names] + [function(source, "point", "namedAny")]
    result["ReferencePoseGeometry.swift"] = HEADER + "import Foundation\nimport CoreGraphics\n\nstruct ReferencePoseGeometry {\n" + "\n\n".join(pure) + "\n}\n"
    result["ReferenceMeasurementAlgorithms.swift"] = HEADER + "import UIKit\nimport Vision\nimport CoreImage\n\nstruct ReferenceMeasurementAlgorithms {\n    private let coachingEngine = CoachingEngine()\n" + "\n\n".join(methods) + "\n}\n"
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, content in outputs().items():
        path = DEST / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Native processing export is stale: {name}")
        else:
            path.write_text(content, encoding="utf-8")
    print("Native processing exports match the reference" if args.check else "Exported native processing reference")


if __name__ == "__main__":
    main()
