// Autogenerated from Pigeon (v26.1.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.dalicamera.dali_camera_platform

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object CameraApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class CameraSnapshot (
  val ready: Boolean,
  val front: Boolean,
  val configurationId: String,
  val aspectRatio: Double,
  val minimumEV: Double,
  val maximumEV: Double,
  val currentEV: Double,
  val supportsLock: Boolean,
  val locked: Boolean,
  val minimumZoom: Double? = null,
  val maximumZoom: Double? = null,
  val currentZoom: Double? = null,
  val supportsTap: Boolean? = null,
  val minimumISO: Double? = null,
  val maximumISO: Double? = null,
  val minimumShutter: Double? = null,
  val maximumShutter: Double? = null,
  val currentISO: Double? = null,
  val currentShutter: Double? = null,
  val manualExposure: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CameraSnapshot {
      val ready = pigeonVar_list[0] as Boolean
      val front = pigeonVar_list[1] as Boolean
      val configurationId = pigeonVar_list[2] as String
      val aspectRatio = pigeonVar_list[3] as Double
      val minimumEV = pigeonVar_list[4] as Double
      val maximumEV = pigeonVar_list[5] as Double
      val currentEV = pigeonVar_list[6] as Double
      val supportsLock = pigeonVar_list[7] as Boolean
      val locked = pigeonVar_list[8] as Boolean
      val minimumZoom = pigeonVar_list[9] as Double?
      val maximumZoom = pigeonVar_list[10] as Double?
      val currentZoom = pigeonVar_list[11] as Double?
      val supportsTap = pigeonVar_list[12] as Boolean?
      val minimumISO = pigeonVar_list[13] as Double?
      val maximumISO = pigeonVar_list[14] as Double?
      val minimumShutter = pigeonVar_list[15] as Double?
      val maximumShutter = pigeonVar_list[16] as Double?
      val currentISO = pigeonVar_list[17] as Double?
      val currentShutter = pigeonVar_list[18] as Double?
      val manualExposure = pigeonVar_list[19] as Boolean?
      return CameraSnapshot(ready, front, configurationId, aspectRatio, minimumEV, maximumEV, currentEV, supportsLock, locked, minimumZoom, maximumZoom, currentZoom, supportsTap, minimumISO, maximumISO, minimumShutter, maximumShutter, currentISO, currentShutter, manualExposure)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ready,
      front,
      configurationId,
      aspectRatio,
      minimumEV,
      maximumEV,
      currentEV,
      supportsLock,
      locked,
      minimumZoom,
      maximumZoom,
      currentZoom,
      supportsTap,
      minimumISO,
      maximumISO,
      minimumShutter,
      maximumShutter,
      currentISO,
      currentShutter,
      manualExposure,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CameraSnapshot) {
      return false
    }
    if (this === other) {
      return true
    }
    return CameraApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PhotoHandle (
  val path: String,
  val id: String,
  val unsaved: Boolean,
  val mimeType: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PhotoHandle {
      val path = pigeonVar_list[0] as String
      val id = pigeonVar_list[1] as String
      val unsaved = pigeonVar_list[2] as Boolean
      val mimeType = pigeonVar_list[3] as String?
      return PhotoHandle(path, id, unsaved, mimeType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      id,
      unsaved,
      mimeType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PhotoHandle) {
      return false
    }
    if (this === other) {
      return true
    }
    return CameraApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class CameraApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CameraSnapshot.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PhotoHandle.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CameraSnapshot -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PhotoHandle -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CameraHostApi {
  fun start(front: Boolean, callback: (Result<CameraSnapshot>) -> Unit)
  fun stop()
  fun capture(callback: (Result<PhotoHandle>) -> Unit)
  fun recover(): PhotoHandle?
  fun save(photo: PhotoHandle, callback: (Result<Unit>) -> Unit)
  fun discard(photo: PhotoHandle)
  fun share(photo: PhotoHandle, callback: (Result<Unit>) -> Unit)
  fun pickPhoto(callback: (Result<PhotoHandle?>) -> Unit)
  fun render(original: PhotoHandle, rotationDegrees: Double, crop: Boolean, strength: Double, callback: (Result<PhotoHandle>) -> Unit)
  fun setControls(configurationId: String, ev: Double, locked: Boolean, callback: (Result<CameraSnapshot>) -> Unit)
  fun renderStyle(original: PhotoHandle, matrix: List<Double>, softness: Double, detail: Double, watermarkPath: String?, callback: (Result<PhotoHandle>) -> Unit)
  fun renderFilter(original: PhotoHandle, matrix: List<Double>, parameters: List<Double>, watermarkPath: String?, callback: (Result<PhotoHandle>) -> Unit)
  fun setVoicePhrase(phrase: String)
  fun releasePhoto(photo: PhotoHandle)
  fun setZoom(configurationId: String, zoom: Double, callback: (Result<CameraSnapshot>) -> Unit)
  fun meter(configurationId: String, x: Double, y: Double, callback: (Result<CameraSnapshot>) -> Unit)
  fun setManualExposure(configurationId: String, seconds: Double?, iso: Double?, callback: (Result<CameraSnapshot>) -> Unit)
  fun openSettings()
  fun setVoiceEnabled(enabled: Boolean, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by CameraHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CameraApiPigeonCodec()
    }
    /** Sets up an instance of `CameraHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CameraHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val frontArg = args[0] as Boolean
            api.start(frontArg) { result: Result<CameraSnapshot> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CameraApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CameraApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stop()
              listOf(null)
            } catch (exception: Throwable) {
              CameraApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.capture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.capture{ result: Result<PhotoHandle> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CameraApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CameraApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.recover$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.recover())
            } catch (exception: Throwable) {
              CameraApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.save$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val photoArg = args[0] as PhotoHandle
            api.save(photoArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CameraApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(CameraApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.discard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val photoArg = args[0] as PhotoHandle
            val wrapped: List<Any?> = try {
              api.discard(photoArg)
              listOf(null)
            } catch (exception: Throwable) {
              CameraApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.share$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val photoArg = args[0] as PhotoHandle
            api.share(photoArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CameraApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(CameraApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.pickPhoto$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.pickPhoto{ result: Result<PhotoHandle?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CameraApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CameraApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.render$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val originalArg = args[0] as PhotoHandle
            val rotationDegreesArg = args[1] as Double
            val cropArg = args[2] as Boolean
            val strengthArg = args[3] as Double
            api.render(originalArg, rotationDegreesArg, cropArg, strengthArg) { result: Result<PhotoHandle> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CameraApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CameraApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.setControls$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configurationIdArg = args[0] as String
            val evArg = args[1] as Double
            val lockedArg = args[2] as Boolean
            api.setControls(configurationIdArg, evArg, lockedArg) { result: Result<CameraSnapshot> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CameraApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CameraApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.renderStyle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val originalArg = args[0] as PhotoHandle
            val matrixArg = args[1] as List<Double>
            val softnessArg = args[2] as Double
            val detailArg = args[3] as Double
            val watermarkPathArg = args[4] as String?
            api.renderStyle(originalArg, matrixArg, softnessArg, detailArg, watermarkPathArg) { result: Result<PhotoHandle> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CameraApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CameraApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.renderFilter$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val originalArg = args[0] as PhotoHandle
            val matrixArg = args[1] as List<Double>
            val parametersArg = args[2] as List<Double>
            val watermarkPathArg = args[3] as String?
            api.renderFilter(originalArg, matrixArg, parametersArg, watermarkPathArg) { result: Result<PhotoHandle> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CameraApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CameraApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.setVoicePhrase$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val phraseArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setVoicePhrase(phraseArg)
              listOf(null)
            } catch (exception: Throwable) {
              CameraApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.releasePhoto$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val photoArg = args[0] as PhotoHandle
            val wrapped: List<Any?> = try {
              api.releasePhoto(photoArg)
              listOf(null)
            } catch (exception: Throwable) {
              CameraApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.setZoom$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configurationIdArg = args[0] as String
            val zoomArg = args[1] as Double
            api.setZoom(configurationIdArg, zoomArg) { result: Result<CameraSnapshot> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CameraApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CameraApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.meter$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configurationIdArg = args[0] as String
            val xArg = args[1] as Double
            val yArg = args[2] as Double
            api.meter(configurationIdArg, xArg, yArg) { result: Result<CameraSnapshot> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CameraApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CameraApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.setManualExposure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configurationIdArg = args[0] as String
            val secondsArg = args[1] as Double?
            val isoArg = args[2] as Double?
            api.setManualExposure(configurationIdArg, secondsArg, isoArg) { result: Result<CameraSnapshot> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CameraApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CameraApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.openSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openSettings()
              listOf(null)
            } catch (exception: Throwable) {
              CameraApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dali_camera_platform.CameraHostApi.setVoiceEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            api.setVoiceEnabled(enabledArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CameraApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CameraApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class CameraEvents(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CameraEvents. */
    val codec: MessageCodec<Any?> by lazy {
      CameraApiPigeonCodec()
    }
  }
  fun analysis(jsonArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.dali_camera_platform.CameraEvents.analysis$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(jsonArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CameraApiPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
  fun state(snapshotArg: CameraSnapshot, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.dali_camera_platform.CameraEvents.state$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(snapshotArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CameraApiPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
  fun error(codeArg: String, messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.dali_camera_platform.CameraEvents.error$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(codeArg, messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CameraApiPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
  fun voiceShutter(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.dali_camera_platform.CameraEvents.voiceShutter$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CameraApiPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
}
